name: GitHub Pages for Slide
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install font
      run: sudo apt update && sudo apt install fonts-noto

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Generate OGP Images
      run: npx @marp-team/marp-cli@latest -I slides -o docs --image jpeg

    - name: Copy Images to docs
      run: cp -r slides/images docs/images

    - name: Build Marp
      run: npx @marp-team/marp-cli@latest -I slides -o docs

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        destination_dir: ./docs
